version: "3.8"

services:
  db:
    image: postgres
    hostname: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # redis:
  #   image: redis

  api:
    build: api
    restart: always
    command: python api/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/api
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
      # - redis

  rtmp:
    build: rtmp
    restart: always
    ports:
      - "1935:1935"
      - "8001:8001"
    links:
      - db
    depends_on:
      - api
      - db
      # - redis

  web:
    build: web
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api
      - rtmp
