version: "3.8"

services:
  db:
    image: postgres
    hostname: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    build: api
    restart: always
    command: python api/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/api
    ports:
      - "8000:8000"
    depends_on:
      - db

  web:
    build:
      context: web
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    depends_on:
      - api
