# Generated by Django 2.2.18 on 2021-04-18 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stream_key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
