# Generated by Django 3.2.1 on 2021-10-31 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_stream_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stream_key',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
