# Generated by Django 2.2.18 on 2021-03-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20210317_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistvideo',
            options={'ordering': ['position'], 'verbose_name': 'Playlist Video', 'verbose_name_plural': 'Playlist Videos'},
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='videos',
        ),
    ]
