# Generated by Django 2.2.18 on 2021-03-22 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20210318_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), to='video.SubCategory'),
        ),
        migrations.AlterField(
            model_name='playlistview',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlistview_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videoview',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='videoview_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
