# Generated by Django 2.2.18 on 2021-03-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='replycomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Reply Comment', 'verbose_name_plural': 'Reply Comments'},
        ),
    ]
