# Generated by Django 2.2.18 on 2021-04-06 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liking', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videorating_user', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_video_video', to='video.Video')),
            ],
            options={
                'verbose_name': 'Video Rating',
                'verbose_name_plural': 'Video Ratings',
            },
        ),
        migrations.CreateModel(
            name='ReplyCommentRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liking', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reply_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_reply_comment_reply_comment', to='comments.ReplyComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replycommentrating_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reply Comment Rating',
                'verbose_name_plural': 'Reply Comment Ratings',
            },
        ),
        migrations.CreateModel(
            name='CommentRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liking', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_comment_comment', to='comments.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentrating_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment Rating',
                'verbose_name_plural': 'Comment Ratings',
            },
        ),
    ]
