# Generated by Django 2.2.18 on 2021-03-22 12:20

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210315_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.get_user_upload_to, verbose_name='background'),
        ),
    ]
