# Generated by Django 2.2.18 on 2021-04-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20210421_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), related_name='video_subcategory', to='video.Subcategory'),
        ),
    ]